// dummydata/listings.ts
import { Listing } from "@/components/ListingCard";

export const LISTINGS: Listing[] = [
  {
    id: "1",
    title: "Mercedex Benz",
    price: "$27,900",
    km: "42,000km",
    views: 950,
    likes: 35,
    messages: 35,
    status: "Active",
    image: require("@/assets/images/car.jpg"),
  },
  {
    id: "2",
    title: "Toyota Prius", 
    price: "$18,500",
    km: "58,300km",
    views: 412,
    likes: 18,
    messages: 6,
    status: "Paused",
    image: require("@/assets/images/car.jpg"),
  },
  {
    id: "3",
    title: "Honda Civic",
    price: "$21,200",
    km: "32,100km",
    views: 720,
    likes: 48,
    messages: 12,
    status: "Active",
    image: require("@/assets/images/car.jpg"),
  },
  {
    id: "4",
    title: "Nissan Altima",
    price: "$16,900",
    km: "75,000km",
    views: 180,
    likes: 9,
    messages: 2,
    status: "Draft",
    image: require("@/assets/images/car.jpg"),
  },
  {
    id: "5",
    title: "Range Rover Evoque",
    price: "$39,800",
    km: "21,500km",
    views: 1300,
    likes: 220,
    messages: 40,
    status: "Active",
    image: require("@/assets/images/car.jpg"),
  },
];
